sudo: required

language: go

services:
    - docker

go:
    - 1.7
before_install:
install:
    - go build .
script:
    - echo "test skip"
before_deploy:
    - "./release"
deploy:
    provider: releases
    api_key:
        secure: VlTP7AlzVV2PuCU+hRPMYW5H050PvMufxPLNmurqziDUlHSDmvyWZc6cEicdXbZNI7ANr9R6a+OYUjtZ/uteK6uMkKzMjfWjZCPtu0XXcp23N0ortFgsa4wvbRvC5lHOAdSjDXusCnPebeBfvGcphkws1Ps2Z3OfsfKEAKr5ZUNgI3z7T+wH38hIGrR4rSJoedkjWRmHzPYeJZFnfYezgI5LzfWYpFvf6CU0tIYJs8B2BqRoz/c9so1l6So7jeNd/yHDcAN6+hBxv7ruSRCzzHqyfUfBqT2JlaKZrTZygRc4Iu1pBqefJLLQYBB3DfoOTyAegkwS+hICQml2e1lvDX749k/UwNvmEDYptKp6F+OE7SXMIGxcnRL55Vv0l4nG1h5JFJFvTd0MU/jY33cI6p2uRgZ1LT4/jN737t+9FpM+i8+R0tdM0e9xZRrjpHChZqC9PdC6u0s1qyI02+8w9giNpH4MipgNRR3iXNrtya4bOF5VgYqM0kJTHyHtzoh1yyy+UtnW3W1EGDXkQPluHPM7kdo9xPWrWbxAV9idcZUNdpticnn+6WdFCdYT8hrcUZIiuTavlWhzvn+R2dH5bOSdLigS87KDK9oqPTvVW9FU6i9rVT/w+Y1dpwwhHJz+2H7vwgCKnktx9ZhMav09Xqjej88JwX3YKxc7WONny1g=
    file:
        - "bin/linux/docker-machine-driver-qingcloud-linux-amd64.tar.gz"
        - "bin/darwin/docker-machine-driver-qingcloud-darwin-amd64.tar.gz"
    on:
        repo: yunify/docker-machine-driver-qingcloud
        tags: true
